on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

name: Pull Request Unit Test

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - run: make test